import type { Metadata } from "next";
import { content, languages, routes, type Lang } from "@/content/i18n";
import { site } from "@/content/site.config";

const siteUrl = process.env.SITE_URL ?? site.brand.domain;

/** og.png is generated by `npm run og` and committed — see scripts/build-og.mjs. */
const card = { url: "og.png", width: 1200, height: 630 };

/**
 * Metadata for one page in one language, including the hreflang pairing that
 * tells search engines the two versions are the same page, not duplicates.
 */
/** What every page in a language shares: the base URL and the title template. */
export function layoutMetadata(lang: Lang): Metadata {
  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: `${site.brand.name} — ${content[lang].meta.title}`,
      template: `%s · ${site.brand.name}`,
    },
  };
}

export function pageMetadata(lang: Lang, doc?: "privacy" | "terms"): Metadata {
  const c = content[lang];
  const path = doc ? routes[lang][doc] : routes[lang].home;

  const alternates = Object.fromEntries(
    languages.map((other) => [
      content[other].htmlLang,
      doc ? routes[other][doc] : routes[other].home,
    ]),
  );

  if (doc) {
    return {
      title: c.legal[doc].title,
      description: c.legal[doc].description,
      alternates: { canonical: path, languages: alternates },
      robots: { index: false, follow: true },
    };
  }

  return {
    description: c.meta.description,
    keywords: [...c.meta.keywords],
    alternates: { canonical: path, languages: alternates },
    openGraph: {
      type: "website",
      locale: lang === "es" ? "es_MX" : "en_US",
      url: path,
      siteName: site.brand.name,
      title: `${site.brand.name} — ${c.meta.ogTitle}`,
      description: c.meta.description,
      images: [card],
    },
    twitter: {
      card: "summary_large_image",
      title: `${site.brand.name} — ${c.meta.ogTitle}`,
      description: c.meta.description,
      images: [card.url],
    },
    /* The Pages preview lives on a temporary domain — keep it out of search
       results until the real domain is live. */
    /* Un despliegue de vista previa vive bajo un sub-path y no debe indexarse
       antes que el dominio real; el dominio propio sí. */
    robots: process.env.BASE_PATH ? { index: false, follow: false } : { index: true, follow: true },
  };
}
